In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df =pd.read_csv('diabets.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Age,Outcome
0,2,135,80,33,155,27.1,29,1
1,0,89,66,23,94,28.1,21,0
2,1,118,72,35,120,34.9,25,0
3,3,145,82,30,110,32.5,31,1
4,5,160,74,28,135,34.2,45,1

In [ ]:
df.shape

(37, 8)

In [ ]:
df['Outcome'].value_counts()

Outcome
0    19
1    18
Name: count, dtype: int64

In [ ]:
x =df.drop('Outcome', axis=1)
y =df['Outcome']

In [ ]:
x

    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  Age
0             2      135             80             33      155  27.1   29
1             0       89             66             23       94  28.1   21
2             1      118             72             35      120  34.9   25
3             3      145             82             30      110  32.5   31
4             5      160             74             28      135  34.2   45
5             0       95             70             20       80  26.5   22
6             2      125             68             32      105  30.1   27
7             4      150             78             29      140  33.0   34
8             1      130             60             22       85  28.4   23
9             3      140             75             31      130  32.8   30
10            0       99             64             19       70  25.5   20
11            2      155             82             37      150  36.5   33
12            1      110             68             24       90  27.8   24
13            5      170             80             38      160  37.9   42
14            0       92             65             21       75  26.0   19
15            3      148             76             28      120  31.5   29
16            2      138             74             30      115  29.8   32
17            4      152             82             36      155  35.1   37
18            1      120             70             26       88  27.2   26
19            3      158             85             34      140  36.2   39
20            2      125             72             25      100  29.0   28
21            0      105             68             22       95  26.8   21
22            4      162             80             33      145  34.7   40
23            3      135             78             28      120  32.0   31
24            1      115             65             24       85  28.5   24
25            2      140             74             30      130  33.2   35
26            0      100             66             20       90  27.0   22
27            5      165             82             36      160  38.0   44
28            3      145             76             31      125  32.5   30
29            1      120             70             26       95  28.0   27
30            2      135             75             29      110  30.5   32
31            4      155             80             34      150  36.0   38
32            0       98             64             21       80  25.8   20
33            3      150             78             32      135  33.5   33
34            1      110             68             23       90  27.5   25
35            2      138             72             28      120  31.0   29
36            5      170             85             37      165  37.5   43

In [ ]:
y

0     1
1     0
2     0
3     1
4     1
5     0
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
16    0
17    1
18    0
19    1
20    0
21    0
22    1
23    1
24    0
25    1
26    0
27    1
28    1
29    0
30    0
31    1
32    0
33    1
34    0
35    0
36    1
Name: Outcome, dtype: int64

In [ ]:
x =np.array(x)
y =np.array(y)

In [ ]:
x

array([[  2. , 135. ,  80. ,  33. , 155. ,  27.1,  29. ],
       [  0. ,  89. ,  66. ,  23. ,  94. ,  28.1,  21. ],
       [  1. , 118. ,  72. ,  35. , 120. ,  34.9,  25. ],
       [  3. , 145. ,  82. ,  30. , 110. ,  32.5,  31. ],
       [  5. , 160. ,  74. ,  28. , 135. ,  34.2,  45. ],
       [  0. ,  95. ,  70. ,  20. ,  80. ,  26.5,  22. ],
       [  2. , 125. ,  68. ,  32. , 105. ,  30.1,  27. ],
       [  4. , 150. ,  78. ,  29. , 140. ,  33. ,  34. ],
       [  1. , 130. ,  60. ,  22. ,  85. ,  28.4,  23. ],
       [  3. , 140. ,  75. ,  31. , 130. ,  32.8,  30. ],
       [  0. ,  99. ,  64. ,  19. ,  70. ,  25.5,  20. ],
       [  2. , 155. ,  82. ,  37. , 150. ,  36.5,  33. ],
       [  1. , 110. ,  68. ,  24. ,  90. ,  27.8,  24. ],
       [  5. , 170. ,  80. ,  38. , 160. ,  37.9,  42. ],
       [  0. ,  92. ,  65. ,  21. ,  75. ,  26. ,  19. ],
       [  3. , 148. ,  76. ,  28. , 120. ,  31.5,  29. ],
       [  2. , 138. ,  74. ,  30. , 115. ,  29.8,  32. ],
       [  4. , 152. ,  82. ,  36. , 155. ,  35.1,  37. ],
       [  1. , 120. ,  70. ,  26. ,  88. ,  27.2,  26. ],
       [  3. , 158. ,  85. ,  34. , 140. ,  36.2,  39. ],
       [  2. , 125. ,  72. ,  25. , 100. ,  29. ,  28. ],
       [  0. , 105. ,  68. ,  22. ,  95. ,  26.8,  21. ],
       [  4. , 162. ,  80. ,  33. , 145. ,  34.7,  40. ],
       [  3. , 135. ,  78. ,  28. , 120. ,  32. ,  31. ],
       [  1. , 115. ,  65. ,  24. ,  85. ,  28.5,  24. ],
       [  2. , 140. ,  74. ,  30. , 130. ,  33.2,  35. ],
       [  0. , 100. ,  66. ,  20. ,  90. ,  27. ,  22. ],
       [  5. , 165. ,  82. ,  36. , 160. ,  38. ,  44. ],
       [  3. , 145. ,  76. ,  31. , 125. ,  32.5,  30. ],
       [  1. , 120. ,  70. ,  26. ,  95. ,  28. ,  27. ],
       [  2. , 135. ,  75. ,  29. , 110. ,  30.5,  32. ],
       [  4. , 155. ,  80. ,  34. , 150. ,  36. ,  38. ],
       [  0. ,  98. ,  64. ,  21. ,  80. ,  25.8,  20. ],
       [  3. , 150. ,  78. ,  32. , 135. ,  33.5,  33. ],
       [  1. , 110. ,  68. ,  23. ,  90. ,  27.5,  25. ],
       [  2. , 138. ,  72. ,  28. , 120. ,  31. ,  29. ],
       [  5. , 170. ,  85. ,  37. , 165. ,  37.5,  43. ]])

In [ ]:
y

array([1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1])

In [ ]:
#normalization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x =scaler.fit_transform(x)
x

array([[-0.10226943,  0.11415571,  0.97462431,  0.82537028,  1.40289605,
        -1.07494064, -0.13881943],
       [-1.36359234, -1.86842609, -1.16459346, -1.01431046, -0.82221736,
        -0.80961173, -1.24937484],
       [-0.73293088, -0.61853757, -0.24778584,  1.19330642,  0.12619163,
         0.99462486, -0.69409714],
       [ 0.52839203,  0.54515175,  1.28022685,  0.27346606, -0.23858106,
         0.35783548,  0.13881943],
       [ 1.78971495,  1.19164582,  0.0578167 , -0.09447009,  0.67335067,
         0.80889462,  2.08229141],
       [-1.36359234, -1.60982847, -0.55338838, -1.56621468, -1.33289913,
        -1.23413799, -1.11055542],
       [-0.10226943, -0.31684033, -0.85899092,  0.6414022 , -0.4209674 ,
        -0.27895391, -0.41645828],
       [ 1.15905349,  0.76064977,  0.66902177,  0.08949798,  0.85573701,
         0.49049993,  0.55527771],
       [-0.73293088, -0.10134231, -2.08140108, -1.19827853, -1.15051278,
        -0.73001306, -0.97173599],
       [ 0.52839203,  0.32965373,  0.21061797,  0.45743413,  0.49096432,
         0.43743415,  0.        ],
       [-1.36359234, -1.43743005, -1.470196  , -1.75018276, -1.69767182,
        -1.4994669 , -1.38819427],
       [-0.10226943,  0.9761478 ,  1.28022685,  1.56124257,  1.2205097 ,
         1.41915112,  0.41645828],
       [-0.73293088, -0.9633344 , -0.85899092, -0.83034239, -0.96812644,
        -0.8892104 , -0.83291656],
       [ 1.78971495,  1.62264186,  0.97462431,  1.74521065,  1.58528239,
         1.79061159,  1.66583312],
       [-1.36359234, -1.73912728, -1.31739473, -1.38224661, -1.51528547,
        -1.36680244, -1.5270137 ],
       [ 0.52839203,  0.67445057,  0.36341924, -0.09447009,  0.12619163,
         0.09250657, -0.13881943],
       [-0.10226943,  0.24345452,  0.0578167 ,  0.27346606, -0.05619471,
        -0.35855258,  0.27763885],
       [ 1.15905349,  0.84684898,  1.28022685,  1.3772745 ,  1.40289605,
         1.04769064,  0.97173599],
       [-0.73293088, -0.53233836, -0.55338838, -0.46240624, -1.04108098,
        -1.04840775, -0.55527771],
       [ 0.52839203,  1.10544661,  1.73863066,  1.00933835,  0.85573701,
         1.33955244,  1.24937484],
       [-0.10226943, -0.31684033, -0.24778584, -0.64637431, -0.60335375,
        -0.57081571, -0.27763885],
       [-1.36359234, -1.17883242, -0.85899092, -1.19827853, -0.78574009,
        -1.15453931, -1.24937484],
       [ 1.15905349,  1.27784503,  0.97462431,  0.82537028,  1.03812336,
         0.94155908,  1.38819427],
       [ 0.52839203,  0.11415571,  0.66902177, -0.09447009,  0.12619163,
         0.22517102,  0.13881943],
       [-0.73293088, -0.74783638, -1.31739473, -0.83034239, -1.15051278,
        -0.70348016, -0.83291656],
       [-0.10226943,  0.32965373,  0.0578167 ,  0.27346606,  0.49096432,
         0.54356571,  0.69409714],
       [-1.36359234, -1.39433044, -1.16459346, -1.56621468, -0.96812644,
        -1.10147353, -1.11055542],
       [ 1.78971495,  1.40714384,  1.28022685,  1.3772745 ,  1.58528239,
         1.81714448,  1.94347198],
       [ 0.52839203,  0.54515175,  0.36341924,  0.45743413,  0.30857798,
         0.35783548,  0.        ],
       [-0.73293088, -0.53233836, -0.55338838, -0.46240624, -0.78574009,
        -0.83614462, -0.41645828],
       [-0.10226943,  0.11415571,  0.21061797,  0.08949798, -0.23858106,
        -0.17282234,  0.27763885],
       [ 1.15905349,  0.9761478 ,  0.97462431,  1.00933835,  1.2205097 ,
         1.28648666,  1.11055542],
       [-1.36359234, -1.48052965, -1.470196  , -1.38224661, -1.33289913,
        -1.41986822, -1.38819427],
       [ 0.52839203,  0.76064977,  0.66902177,  0.6414022 ,  0.67335067,
         0.62316439,  0.41645828],
       [-0.73293088, -0.9633344 , -0.85899092, -1.01431046, -0.96812644,
        -0.96880908, -0.69409714],
       [-0.10226943,  0.24345452, -0.24778584, -0.09447009,  0.12619163,
        -0.04015789, -0.13881943],
       [ 1.78971495,  1.62264186,  1.73863066,  1.56124257,  1.76766874,
         1.68448003,  1.80465255]])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
x_train.shape, y_train.shape

((29, 7), (29,))

In [ ]:
x_test.shape, y_test.shape

((8, 7), (8,))